package spinworld

import java.util.List
import java.util.ArrayList

import spinworld.allocators.RandomAllocator
import spinworld.ProvisionPool
import spinworld.actions.*
import spinworld.facts.*
import spinworld.network.*
import spinworld.RoundType

global org.apache.log4j.Logger logger
global org.drools.runtime.StatefulKnowledgeSession session

rule "Random resource allocation"
	no-loop
	when
		$r : Round(type == RoundType.DEMAND, $t : number)
		$n : Network(allocationMethod == Allocation.RANDOM)
		$pool : ProvisionPool(network == $n)
		$poolMembers : List(size > 0) from accumulate(MemberOf(network == $n, $p : particle), collectList($p))
	then
		logger.info("Random order allocation for resources " + $n);
		RandomAllocator.allocate(session, $poolMembers, $pool.getQuantity(), $t);
		
		modify($pool) {
			setQuantity(0);
		}
end
